# -*- coding: utf-8 -*-
"""
카드뉴스 콘텐츠 — 매주 이 파일만 갱신하면 카드가 새로 생성된다.
제품 포지셔닝: 래쉬애딕트=속눈썹 생장(진짜 자람) / 아이원잇=관리용 영양제.
CTA는 전 주제 공통(공식 판매점 등록·문의 → 리즈라인). 8번째 카드는 자동으로 붙는다.
각 주제 cards = 7장(표지+본문6). 카드 타입: cover/statement/point/mentte/checklist/apply.
'mentte'(실전 멘트) 카드는 인스타용 블러 버전(card_4_locked)이 자동 생성된다.
"""

TOPICS = [
    # 01 ─ 업셀링(파일럿, 확정 디자인)
    {"slug":"upselling", "cards":[
        {"type":"cover",
         "title":"객단가 <span class=\"hl\">2배</span>,<br>‘하나 더’ 파는<br><span class=\"hl\">업셀링 공식</span>",
         "sub":"래쉬애딕트로 <b>키우고</b> → 아이원잇으로 <b>완성</b>하는 세트 판매"},
        {"type":"statement","title":"결제 직후가<br><span class=\"hl\">골든타임</span>",
         "note":"대부분 이렇게 끝나요 — “하나 주세요 → 결제 → 끝.”",
         "lead":"이미 ‘산다’고 한 고객은<br><span class=\"blue\">두 번째 제안</span>에 YES가 훨씬 쉽습니다.",
         "tag":"# 일관성의 원리"},
        {"type":"point","badge":"핵심 포인트","title":"업셀링은 <span class=\"hl\">타이밍</span>이 8할",
         "note":"구매를 결정한 직후 = 지갑이 열려 있는 순간.<br>성격이 반대인 제품을 얹으면 자연스럽습니다.",
         "duo":[("래쉬애딕트","키우는 것 · 생장"),("아이원잇","지키는 것 · 관리")],
         "punch":"“키웠으면 <span class=\"blue\">지켜야죠</span>”"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“길이 키우셨으면,<br><span class=\"blue\">아이원잇으로 완성</span>해야죠”",
         "note":"가격을 ‘더 쓰는 것’이 아니라 <b>‘완성하는 것’</b>으로. # 앵커링"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"내 매장, 객단가 새고 있나?",
         "items":["래쉬애딕트만 팔고 <b>관리 언급을 안 한다</b>","묶음(세트) <b>가격이 없다</b>",
                  "업셀을 결제 후가 아닌 <b>상담 초반</b>에 던진다","원장 본인이 <b>세트로 안 써봤다</b>"],
         "footer":"2개 이상이면 <b class=\"blue\">객단가가 새는 중</b>입니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"다음 래쉬애딕트 판매 <span class=\"blue\" style=\"font-weight:900\">3번</span>,<br>결제 직후 딱 한 문장:",
         "quote":"“키웠으면 지켜야죠”",
         "note":"3명 중 <b>1명만</b> 세트로 가도<br>객단가는 이미 올라갑니다."},
        {"type":"closer","badge":"한 끗 차이","title":"추천을 <span class=\"hl\">증거</span>로<br>바꾸는 법",
         "note":"원장님이 직접 ①래쉬애딕트로 키우고 ②아이원잇으로 관리한 <b>비포·애프터</b>를 보여주세요.",
         "punch":"‘추천’이 <span class=\"blue\">‘증거’</span>가 됩니다","tag":"# 사회적 증거"},
    ]},

    # 02 ─ 가격 응대
    {"slug":"price-objection", "cards":[
        {"type":"cover",
         "title":"“비싸요”는<br>거절이 아니라 <span class=\"hl\">질문</span>입니다",
         "sub":"가격 저항, 이 한마디로 넘깁니다"},
        {"type":"statement","title":"여기서 무너지면 끝",
         "note":"“그쵸, 좀 있죠…” 하고 맞장구치는 순간 판매는 종료됩니다.",
         "lead":"‘비싸다’는 건 <span class=\"blue\">‘그만한 가치가 있어?’</span>라는 질문일 뿐.",
         "tag":"# 가격 = 가치 질문"},
        {"type":"point","badge":"핵심 포인트","title":"가격을 <span class=\"hl\">하루값</span>으로 쪼개라",
         "note":"총액은 비싸 보여도, 쓰는 기간으로 나누면 부담이 사라집니다.",
         "duo":[("‘○○만원’","부담 큼"),("‘하루 ○○원’","부담 작음")],
         "punch":"숫자는 그대로, <span class=\"blue\">느낌만</span> 바뀝니다"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“이거 하나면 약 ○개월,<br><span class=\"blue\">하루로 치면</span> 얼마 안 돼요”",
         "note":"‘총액’이 아니라 <b>‘하루 비용’</b>으로 프레임. # 리프레이밍"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"가격 응대, 이렇게 하고 있나?",
         "items":["“비싸죠…” 하고 <b>같이 인정</b>한다","바로 <b>할인부터</b> 꺼낸다",
                  "가치 설명 없이 <b>가격만</b> 말한다","고객이 <b>비교할 기준</b>을 안 준다"],
         "footer":"하나라도 O면 가격에서 계속 놓칩니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"다음에 “비싸요” 들으면<br>깎지 말고:",
         "quote":"“하루로 치면 ○원이에요”",
         "note":"가격을 <b>기간으로 나눠</b> 말하기 — 딱 이것만."},
        {"type":"closer","badge":"한 끗 차이","title":"할인보다 <span class=\"hl\">비교 기준</span>",
         "note":"깎아주지 말고 시술 1회 비용과 나란히 놓으세요. <b>비싼 게 싸 보입니다.</b>",
         "punch":"가격은 <span class=\"blue\">혼자일 때</span> 비쌉니다","tag":"# 앵커링"},
    ]},

    # 03 ─ 재구매 설계
    {"slug":"repurchase", "cards":[
        {"type":"cover",
         "title":"영양제 매출은<br><span class=\"hl\">두 번째 구매</span>에서<br>갈립니다",
         "sub":"한 번 팔고 끝? <b>재구매</b>를 설계하세요"},
        {"type":"statement","title":"한 번 팔고 끝나는 이유",
         "note":"재구매 ‘타이밍’을 안 심어서예요.<br>고객은 다 쓴 것도 잊어버립니다.",
         "lead":"판매 시점에 <span class=\"blue\">다음 구매를 예약</span>시켜야 합니다.",
         "tag":"# 재구매 설계"},
        {"type":"point","badge":"핵심 포인트","title":"다 쓸 때쯤을 <span class=\"hl\">미리 알려줘라</span>",
         "note":"제품을 건네며 ‘언제 떨어지는지 + 그때 뭘 할지’를 함께 각인시키세요.",
         "duo":[("사용 주기 안내","기억에 남음"),("리터치와 겹치기","방문=재구매")],
         "punch":"잊기 전에 <span class=\"blue\">먼저</span> 말하세요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“이거 대략 ○주 쓰시는데,<br>그때쯤 <span class=\"blue\">리터치랑 같이</span> 챙기면 딱이에요”",
         "note":"재구매 시점을 <b>다음 방문에 얹기</b>. # 앵커링"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"재구매, 새고 있진 않나?",
         "items":["<b>사용 주기</b>를 안 알려준다","재방문 때 <b>제품 얘길</b> 안 한다",
                  "다 썼는지 <b>확인</b>을 안 한다","<b>재구매 혜택·묶음</b>이 없다"],
         "footer":"재구매는 저절로 오지 않습니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"다음 판매 때<br>제품 건네며 한마디:",
         "quote":"“○주 뒤, 리터치 때 같이 봐요”",
         "note":"<b>사용 주기 한마디</b>만 붙이기."},
        {"type":"closer","badge":"한 끗 차이","title":"신규 1명 &lt; <span class=\"hl\">재구매 1명</span>",
         "note":"이미 효과 본 고객은 설득이 필요 없어요. <b>가장 쉬운 매출</b>입니다.",
         "punch":"제일 싼 고객은 <span class=\"blue\">단골</span>입니다","tag":"# 리텐션"},
    ]},

    # 04 ─ 효과 없다는 고객
    {"slug":"no-effect", "cards":[
        {"type":"cover",
         "title":"“효과 없어요”는<br>대부분 <span class=\"hl\">사용법</span> 문제",
         "sub":"환불 대신 <b>재구매</b>로 되돌리는 법"},
        {"type":"statement","title":"여기서 지면 둘 다 잃어요",
         "note":"반박하면 고객은 방어부터.<br>매출도 신뢰도 같이 날아갑니다.",
         "lead":"‘효과 없다’ = <span class=\"blue\">도와달라는 신호</span>.",
         "tag":"# 컴플레인 = 기회"},
        {"type":"point","badge":"핵심 포인트","title":"반박 말고 <span class=\"hl\">사용부터 점검</span>",
         "note":"언제·어디에·얼마나 바르는지 되물으면, 대부분 원인이 바로 나옵니다.",
         "duo":[("사용 점검","원인 발견"),("루틴 교정","효과 체감")],
         "punch":"고치는 순간 <span class=\"blue\">신뢰</span>가 회복됩니다"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“혹시 ○에 바르셨어요?<br><span class=\"blue\">이 위치가</span> 절반이에요”",
         "note":"지적이 아니라 <b>코칭 톤</b>으로. # 사용법 코칭"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"이 응대, 하고 있진 않나?",
         "items":["“원래 그래요”로 <b>넘긴다</b>","바로 <b>환불부터</b> 해준다",
                  "<b>사용법을</b> 다시 안 알려준다","<b>다음 점검 약속</b>을 안 잡는다"],
         "footer":"응대가 곧 재구매 기회입니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"불만을 들으면<br>반박 말고 먼저:",
         "quote":"“어떻게 쓰고 계세요?”",
         "note":"되묻고, <b>사용법 한 번 더</b> 잡아주기."},
        {"type":"closer","badge":"한 끗 차이","title":"잘 푼 불만은 <span class=\"hl\">단골</span>이 된다",
         "note":"문제를 해결해준 원장을 고객은 <b>더 신뢰</b>합니다.",
         "punch":"불만 고객 = <span class=\"blue\">미래 단골</span>","tag":"# 신뢰 회복"},
    ]},

    # 05 ─ 단독 수요
    {"slug":"standalone-demand", "cards":[
        {"type":"cover",
         "title":"시술 안 하는 날에도<br><span class=\"hl\">매출</span>이 도는 샵",
         "sub":"영양제 <b>단독 수요</b>를 여는 법"},
        {"type":"statement","title":"이 매출이 안 생기는 이유",
         "note":"영양제를 ‘시술 부가상품’으로만 두면,<br>시술 없인 안 팔려요.",
         "lead":"<span class=\"blue\">단독으로 사러 올 이유</span>를 만들어야 합니다.",
         "tag":"# 단독 수요"},
        {"type":"point","badge":"핵심 포인트","title":"제품을 <span class=\"hl\">루틴·선물</span>로 팔아라",
         "note":"‘다 떨어지면 또’ + ‘지인 선물’ 두 갈래가 단독 구매를 만듭니다.",
         "duo":[("재고 루틴","반복 구매"),("선물 수요","신규 유입")],
         "punch":"시술 없이도 <span class=\"blue\">이유</span>가 있으면 옵니다"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“연장 안 하실 때도<br><span class=\"blue\">관리는 계속</span> 하셔야 해요”",
         "note":"제품을 <b>시술과 분리</b>해 각인. # 단독 포지셔닝"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"단독 판매, 막혀 있진 않나?",
         "items":["제품이 <b>시술 예약자에게만</b> 보인다","<b>택배·픽업</b> 안내가 없다",
                  "<b>선물용</b> 제안을 안 한다","‘다 쓰면 연락’ <b>창구</b>가 없다"],
         "footer":"살 길을 안 열어두면 안 삽니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"이번 주 3명에게<br>단독 창구 열기:",
         "quote":"“다 쓰시면 톡 주세요, 챙겨둘게요”",
         "note":"<b>단독 재구매 창구</b> 열어두기."},
        {"type":"closer","badge":"한 끗 차이","title":"‘사러 오는’ 제품이<br><span class=\"hl\">진짜 매출</span>",
         "note":"시술에 얹는 매출엔 한계가 있어요. <b>단독 수요</b>가 매장을 키웁니다.",
         "punch":"제품이 <span class=\"blue\">혼자</span> 팔릴 때 남는 장사","tag":"# 단독 매출"},
    ]},

    # 06 ─ 비대면 클로징
    {"slug":"dm-closing", "cards":[
        {"type":"cover",
         "title":"“생각해볼게요” 하고<br>나간 고객, <span class=\"hl\">되살리는 법</span>",
         "sub":"카톡 한 통으로 끝내는 <b>비대면 클로징</b>"},
        {"type":"statement","title":"제일 아까운 손님",
         "note":"매장에서 못 판 걸 그냥 포기하면,<br>이미 관심 있던 고객을 버리는 겁니다.",
         "lead":"나간 뒤 <span class=\"blue\">1~2일</span>이 골든타임.",
         "tag":"# 사후 접촉"},
        {"type":"point","badge":"핵심 포인트","title":"‘영업’ 말고 <span class=\"hl\">안부</span>로",
         "note":"제품 얘기부터 꺼내면 부담. 관리 안부로 자연스럽게 다시 연결합니다.",
         "duo":[("관리 안부","경계 낮춤"),("맞춤 제안","전환 올림")],
         "punch":"파는 말보다 <span class=\"blue\">챙기는 말</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“고객님, 지난번 말씀드린 그거<br><span class=\"blue\">마침 ○해서</span> 톡 드려요”",
         "note":"안부 → 제안 → 결제까지 <b>3문장</b>. # 비대면 클로징"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"사후 접촉, 하고 있나?",
         "items":["나간 고객은 <b>그냥 잊는다</b>","<b>연락처</b>를 안 남긴다",
                  "<b>결제 링크·계좌</b> 안내가 없다","<b>타이밍(1~2일)</b>을 놓친다"],
         "footer":"관심은 이틀이면 식습니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"망설이다 간 고객에게<br>다음날 톡 한 통:",
         "quote":"“생각 정리되셨어요? 편히 톡 주세요”",
         "note":"<b>안부 톡 한 통</b> 보내기."},
        {"type":"closer","badge":"한 끗 차이","title":"매장 밖에서 <span class=\"hl\">절반</span>이<br>결정된다",
         "note":"요즘 고객은 나가서 톡으로 삽니다. <b>창구가 없으면</b> 그 매출은 사라져요.",
         "punch":"<span class=\"blue\">대화</span>가 열려 있어야 팔립니다","tag":"# 온라인 접점"},
    ]},

    # 07 ─ 후기 활용
    {"slug":"review-leverage", "cards":[
        {"type":"cover",
         "title":"잘 찍은 후기 1장 =<br><span class=\"hl\">광고 10개</span>",
         "sub":"후기로 <b>신규와 재구매</b>를 동시에"},
        {"type":"statement","title":"후기가 없어서가 아니라",
         "note":"요청이 부담스러워 안 받을 뿐.<br>그래서 강력한 증거를 매번 놓칩니다.",
         "lead":"후기는 <span class=\"blue\">부탁이 아니라 루틴</span>.",
         "tag":"# 사회적 증거"},
        {"type":"point","badge":"핵심 포인트","title":"만족한 <span class=\"hl\">그 순간</span>에 받아라",
         "note":"시술·변화가 가장 예쁠 때가 후기 골든타임. 미루면 못 받습니다.",
         "duo":[("타이밍 요청","수락률 올림"),("재활용","신규 유입")],
         "punch":"가장 예쁠 때 <span class=\"blue\">바로</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“결과 너무 예쁜데<br><span class=\"blue\">○만 살짝</span> 찍어드려도 될까요?”",
         "note":"부담 없는 <b>요청 한 문장</b>. # 후기 요청"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"후기, 놓치고 있진 않나?",
         "items":["요청 자체를 <b>안 한다</b>","타이밍이 <b>지나서</b> 부탁한다",
                  "받은 후기를 <b>안 써먹는다</b>","<b>재방문 유도</b> 문구가 없다"],
         "footer":"안 받으면 증거가 안 쌓입니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"가장 만족한 고객에게<br>이번 주 3장만:",
         "quote":"“이 컷 후기로 써도 될까요?”",
         "note":"<b>후기 3장</b> 확보하기."},
        {"type":"closer","badge":"한 끗 차이","title":"내 말보다 <span class=\"hl\">남의 후기</span>",
         "note":"원장이 백 번 말하는 것보다 <b>고객 한 명의 후기</b>가 셉니다.",
         "punch":"증거는 <span class=\"blue\">고객 입</span>에서","tag":"# 사회적 증거"},
    ]},

    # 08 ─ 오프닝 멘트
    {"slug":"opening-line", "cards":[
        {"type":"cover",
         "title":"영양제는 설명이 아니라<br><span class=\"hl\">한 문장</span>으로 팔린다",
         "sub":"진열대 앞 3초, 고객이 <b>먼저 묻게</b>"},
        {"type":"statement","title":"진열만 하면 그냥 지나가요",
         "note":"제품을 놔두는 것과 파는 건 다릅니다.<br>말 한마디가 없으면 안 물어봐요.",
         "lead":"고객이 <span class=\"blue\">먼저 질문하게</span> 만들어야 합니다.",
         "tag":"# 오프닝"},
        {"type":"point","badge":"핵심 포인트","title":"호기심을 <span class=\"hl\">먼저</span> 건드려라",
         "note":"‘사세요’가 아니라 ‘원장들이 제일 많이 찾는 거’ 식으로 궁금하게.",
         "duo":[("호기심 오프닝","질문 유도"),("자연 상담","부담 낮춤")],
         "punch":"묻게 만들면 <span class=\"blue\">반은</span> 판 것"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“어? 그거 원장님들이<br><span class=\"blue\">제일 많이</span> 찾는 거예요”",
         "note":"호기심 자극 <b>오프닝 한마디</b>. # 후킹"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"진열, 죽어 있진 않나?",
         "items":["<b>잘 안 보이는 곳</b>에 있다","<b>가격·효과 POP</b>가 없다",
                  "<b>먼저 말을</b> 안 건다","원장이 안 써봐서 <b>설명을 못 한다</b>"],
         "footer":"안 보이고 말 없으면 안 팔립니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"계산대 앞 고객에게<br>지나갈 때 한마디:",
         "quote":"“이거 궁금해하시는 분 많아요”",
         "note":"<b>오프닝 한마디</b> 던지기."},
        {"type":"closer","badge":"한 끗 차이","title":"위치가 <span class=\"hl\">매출</span>을 정한다",
         "note":"계산대·거울 옆 눈높이. <b>보이는 만큼</b> 팔립니다.",
         "punch":"안 보이면 <span class=\"blue\">없는</span> 제품","tag":"# 진열"},
    ]},

    # 09 ─ 상태 안 좋은 고객
    {"slug":"gentle-delivery", "cards":[
        {"type":"cover",
         "title":"“상하셨네요” 한마디가<br><span class=\"hl\">판매</span>를 망칩니다",
         "sub":"기분 안 상하게 <b>권하는 법</b>"},
        {"type":"statement","title":"팩트라도 지적이면 방어",
         "note":"속눈썹 상태를 곧이곧대로 말하면,<br>고객은 사기 전에 마음부터 닫아요.",
         "lead":"문제 지적 대신 <span class=\"blue\">더 예뻐질 여지</span>로.",
         "tag":"# 전달법"},
        {"type":"point","badge":"핵심 포인트","title":"‘문제’를 <span class=\"hl\">‘가능성’</span>으로",
         "note":"지금을 깎지 말고, ‘여기에 이것만 더하면’으로 미래를 보여주세요.",
         "duo":[("현재 인정","경계 낮춤"),("가능성 제시","기대 올림")],
         "punch":"깎지 말고 <span class=\"blue\">키워</span> 말하기"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“지금도 예쁜데,<br><span class=\"blue\">○만 채우면</span> 훨씬 완성돼요”",
         "note":"긍정 프레임으로 <b>순화</b>. # 완곡 화법"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"이렇게 말하고 있진 않나?",
         "items":["“많이 상하셨다”고 <b>단정</b>한다","원인을 <b>고객 탓</b>으로 말한다",
                  "해결책 없이 <b>문제만</b> 짚는다","<b>표정·말투</b>가 걱정스럽다"],
         "footer":"말투 하나에 지갑이 닫힙니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"상태가 아쉬운 고객에게<br>‘상했다’ 대신:",
         "quote":"“여기만 보완하면 완성돼요”",
         "note":"<b>‘완성’으로 바꿔</b> 말하기."},
        {"type":"closer","badge":"한 끗 차이","title":"사람은 <span class=\"hl\">희망</span>에<br>지갑을 연다",
         "note":"불안이 아니라 <b>기대</b>를 팔아야 자연스럽게 삽니다.",
         "punch":"겁주지 말고 <span class=\"blue\">그려</span> 주세요","tag":"# 긍정 프레임"},
    ]},

    # 10 ─ 매장 3접점
    {"slug":"instore-3touch", "cards":[
        {"type":"cover",
         "title":"SNS 안 해도<br><span class=\"hl\">잘 파는</span> 샵의 비밀",
         "sub":"매장 안 <b>3접점</b>만으로 파는 법"},
        {"type":"statement","title":"홍보를 못 해서가 아니라",
         "note":"‘팔 자리’를 안 만들어서예요.<br>매장 동선에 접점이 없으면 안 팔립니다.",
         "lead":"상담·시술·결제 <span class=\"blue\">3접점</span>에 심으세요.",
         "tag":"# 오프라인 세일즈"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">3번</span> 자연스럽게 스친다",
         "note":"한 번에 팔지 말고, 상담·시술 후·결제 때 한마디씩 반복 노출.",
         "duo":[("접점 반복","각인 올림"),("작은 언급","부담 낮춤")],
         "punch":"세 번 스치면 <span class=\"blue\">기억</span>에 남아요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“시술 끝나고 딱 한 문장 —<br><span class=\"blue\">집 관리는</span> 이걸로 하세요”",
         "note":"접점별 <b>한 문장</b>. # 반복 노출"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"매장 접점, 비어 있진 않나?",
         "items":["상담 때 <b>제품 언급</b>이 없다","시술 후 <b>안내</b>가 없다",
                  "결제 때 <b>한마디</b>가 없다","원장이 안 써서 <b>자신이 없다</b>"],
         "footer":"접점이 없으면 SNS도 소용없어요"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"시술 마무리마다<br>결제 전 한 문장:",
         "quote":"“집에서 이거 하나면 관리 끝이에요”",
         "note":"<b>결제 전 한 문장</b> 고정으로 넣기."},
        {"type":"closer","badge":"한 끗 차이","title":"SNS는 거들 뿐,<br><span class=\"hl\">매장</span>이 판다",
         "note":"결국 눈앞의 고객에게 파는 게 기본. <b>접점부터</b> 채우세요.",
         "punch":"가까운 <span class=\"blue\">한 명</span>부터","tag":"# 기본기"},
    ]},
]
