# -*- coding: utf-8 -*-
"""
카드뉴스 콘텐츠 — 매주 이 파일만 갱신하면 카드가 새로 생성된다.
제품 포지셔닝: 래쉬애딕트=속눈썹 생장(진짜 자람) / 아이원잇=관리용 영양제.
CTA는 전 주제 공통(공식 판매점 등록·문의 → 리즈라인). 8번째 카드는 자동으로 붙는다.
각 주제 cards = 7장(표지+본문6). 카드 타입: cover/statement/point/mentte/checklist/apply/closer.
'mentte'(실전 멘트) 카드는 인스타용 블러 버전(card_4_locked)이 자동 생성된다.

[배치2] 원장님이 '고객에게' 파는 세일즈 자료 — 완전히 새 주제 10개.
강조: <span class="hl">파란박스</span> / <span class="blue">파란글씨</span> / <b>굵게</b> / <br>줄바꿈.
"""

TOPICS = [
    # 01 ─ 연장만 하려는 고객
    {"slug":"extend-only", "cards":[
        {"type":"cover",
         "title":"“연장만 할게요”에서<br><span class=\"hl\">관리까지</span> 파는 법",
         "sub":"연장 고객이 곧 <b>영양제 1순위</b> 고객입니다"},
        {"type":"statement","title":"연장만 받고 끝?<br>가장 아까운 손님",
         "note":"연장을 반복할수록 자연모는 더 약해집니다.<br>그런데 아무도 안 말해줘요.",
         "lead":"연장 고객이야말로 <span class=\"blue\">관리가 가장 급한</span> 고객입니다.",
         "tag":"# 숨은 수요"},
        {"type":"point","badge":"핵심 포인트","title":"연장 <span class=\"hl\">직후</span>가 제안 타이밍",
         "note":"방금 예뻐진 걸 본 순간, ‘이 상태 유지’ 제안이 가장 잘 먹힙니다.",
         "duo":[("연장","예뻐짐"),("영양제","유지·보호")],
         "punch":"“예뻐졌으니 <span class=\"blue\">지켜야죠</span>”"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“연장 자주 하시면 자연모가 약해져요.<br><span class=\"blue\">이걸로 받쳐주면</span> 훨씬 오래가요”",
         "note":"지적이 아니라 <b>‘더 오래 예쁘게’</b>로. # 가치 전환"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"연장 고객, 그냥 보내고 있나?",
         "items":["연장만 받고 <b>관리 얘긴</b> 안 한다","자연모 상태를 <b>안 짚어</b>준다",
                  "유지 방법을 <b>안 알려</b>준다","연장 주기와 <b>영양제를</b> 안 엮는다"],
         "footer":"연장 고객은 <b class=\"blue\">영양제 1순위</b>입니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"연장 마무리할 때<br>거울 보여주며:",
         "quote":"“이 상태 오래 가려면 이거예요”",
         "note":"연장 끝에 <b>딱 한 문장</b>만 추가."},
        {"type":"closer","badge":"한 끗 차이","title":"연장은 <span class=\"hl\">반복 방문</span>이다",
         "note":"연장 주기마다 영양제를 엮으면, 올 때마다 매출이 쌓입니다.",
         "punch":"방문이 곧 <span class=\"blue\">재구매</span>","tag":"# 루틴 설계"},
    ]},

    # 02 ─ 의심 많은 고객
    {"slug":"doubt-proof", "cards":[
        {"type":"cover",
         "title":"“진짜 효과 있어요?”<br><span class=\"hl\">눈으로</span> 증명하세요",
         "sub":"말 열 마디보다 <b>사진 한 장</b>"},
        {"type":"statement","title":"말로 설득할수록<br>더 의심해요",
         "note":"“좋아요, 효과 좋아요” 백 번 말해도 안 믿습니다.",
         "lead":"의심 고객은 설득이 아니라 <span class=\"blue\">증거</span>로 넘깁니다.",
         "tag":"# 증거 > 설명"},
        {"type":"point","badge":"핵심 포인트","title":"원장 <span class=\"hl\">본인 변화</span>가 최고 증거",
         "note":"남의 후기보다, 원장이 직접 쓴 비포·애프터가 가장 셉니다.",
         "duo":[("성분 설명","흘려들음"),("사진 1장","바로 납득")],
         "punch":"보여주면 <span class=\"blue\">말이 필요 없어요</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“제가 직접 쓴 거예요.<br><span class=\"blue\">여기 비교해보시면</span> 차이 보이죠?”",
         "note":"폰 사진 한 장이면 끝. # 실물 증거"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"증거, 준비돼 있나?",
         "items":["보여줄 <b>비포·애프터가</b> 없다","원장이 <b>직접 안 써</b>봤다",
                  "효과를 <b>말로만</b> 설명한다","고객 후기를 <b>저장</b>해두지 않았다"],
         "footer":"증거 없는 추천은 안 팔립니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"폰에 사진 폴더 하나:",
         "quote":"“직접 쓴 거예요, 보실래요?”",
         "note":"<b>비포·애프터 3장</b>만 미리 저장."},
        {"type":"closer","badge":"한 끗 차이","title":"백 마디보다<br><span class=\"hl\">한 장</span>",
         "note":"말은 의심받지만 사진은 안 받습니다. 폰 한 장이 클로징합니다.",
         "punch":"보여주는 사람이 <span class=\"blue\">판다</span>","tag":"# 증거 제시"},
    ]},

    # 03 ─ 저가 경쟁 차별화
    {"slug":"value-vs-cheap", "cards":[
        {"type":"cover",
         "title":"옆집이 더 싸도<br><span class=\"hl\">우리서</span> 사게 만드는 법",
         "sub":"가격 경쟁 말고 <b>가치</b>로 지키세요"},
        {"type":"statement","title":"싸움을 가격에서 하면<br>무조건 져요",
         "note":"더 싼 곳은 항상 생깁니다. 가격으로는 끝이 없어요.",
         "lead":"고객은 싼 걸 찾는 게 아니라 <span class=\"blue\">믿을 곳</span>을 찾습니다.",
         "tag":"# 가격 ≠ 선택 기준"},
        {"type":"point","badge":"핵심 포인트","title":"제품이 아니라 <span class=\"hl\">관리</span>를 판다",
         "note":"같은 제품도 ‘내 눈 상태를 봐주는 샵’에서 사면 값이 달라집니다.",
         "duo":[("온라인 최저가","그냥 물건"),("원장 관리","내 맞춤 처방")],
         "punch":"파는 건 제품이 아니라 <span class=\"blue\">신뢰</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“인터넷에도 있죠.<br>근데 <span class=\"blue\">눈 상태 봐가며</span> 챙겨드리는 건 저예요”",
         "note":"가격이 아니라 <b>관리</b>로 차별화. # 가치 차별화"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"가격 경쟁에 끌려가고 있나?",
         "items":["먼저 <b>할인부터</b> 꺼낸다","옆집 가격을 <b>따라</b>간다",
                  "제품만 팔고 <b>관리는</b> 안 판다","우리만의 <b>이유</b>를 말 못 한다"],
         "footer":"싸움터를 <b class=\"blue\">가치로</b> 옮기세요"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"가격 비교당하면<br>깎지 말고:",
         "quote":"“눈 상태 봐가며 챙겨드려요”",
         "note":"<b>관리 한 문장</b>으로 받아치기."},
        {"type":"closer","badge":"한 끗 차이","title":"싼 곳이 아니라<br><span class=\"hl\">믿는 곳</span>",
         "note":"가격은 잊혀도 ‘내 눈 봐준 원장’은 남습니다. 그게 단골을 만듭니다.",
         "punch":"기억되는 건 <span class=\"blue\">사람</span>","tag":"# 관계 구매"},
    ]},

    # 04 ─ 체험 소분으로 본품 연결
    {"slug":"sample-hook", "cards":[
        {"type":"cover",
         "title":"한 번 발라보면<br><span class=\"hl\">사게 됩니다</span>",
         "sub":"체험이 <b>본품 구매</b>로 가는 가장 짧은 길"},
        {"type":"statement","title":"설명보다<br>한 번 써보게 하라",
         "note":"안 써본 제품은 아무리 설명해도 ‘언젠가’로 미뤄집니다.",
         "lead":"‘써봤다’는 경험이 <span class=\"blue\">구매 장벽</span>을 무너뜨립니다.",
         "tag":"# 경험 > 설명"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">짧게·공짜로</span> 경험시켜라",
         "note":"시술 때 한 번 발라드리거나 소분을 쥐여주면, 다음엔 고객이 먼저 찾습니다.",
         "duo":[("말로 설명","남 일"),("직접 발라봄","내 일")],
         "punch":"체험은 <span class=\"blue\">가장 싼 광고</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“오늘 한 번 발라드릴게요.<br><span class=\"blue\">써보고</span> 좋으면 그때 챙기세요”",
         "note":"부담 제로로 손에 쥐여주기. # 체험 먼저"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"체험 설계, 돼 있나?",
         "items":["<b>발라볼 기회</b>를 안 준다","제품을 <b>보여만</b> 준다",
                  "소분·샘플이 <b>없다</b>","체험 후 <b>후속 한마디</b>가 없다"],
         "footer":"경험시키면 <b class=\"blue\">전환율</b>이 다릅니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"시술 마무리에<br>한 번 발라드리며:",
         "quote":"“써보고 좋으면 챙기세요”",
         "note":"<b>체험 한 번</b> 끼워넣기."},
        {"type":"closer","badge":"한 끗 차이","title":"파는 게 아니라<br><span class=\"hl\">경험</span>시킨다",
         "note":"좋은 건 한 번 써보면 압니다. 체험이 설득을 대신합니다.",
         "punch":"써본 고객은 <span class=\"blue\">다시 옵니다</span>","tag":"# 샘플 전략"},
    ]},

    # 05 ─ 계절·시즌 소구
    {"slug":"seasonal", "cards":[
        {"type":"cover",
         "title":"계절 바뀔 때가<br><span class=\"hl\">판매 찬스</span>입니다",
         "sub":"‘지금 필요한 이유’를 <b>계절</b>이 만들어줘요"},
        {"type":"statement","title":"‘언제든 사세요’는<br>아무도 안 사요",
         "note":"필요성에 ‘지금’이 없으면 구매는 계속 미뤄집니다.",
         "lead":"계절은 <span class=\"blue\">지금 사야 할 이유</span>를 만들어줍니다.",
         "tag":"# 지금 사야 할 이유"},
        {"type":"point","badge":"핵심 포인트","title":"계절마다 <span class=\"hl\">다른 걱정</span>을 건드려라",
         "note":"여름엔 땀·눈물로 쉽게 빠지고, 환절기엔 모가 약해집니다. 그 걱정에 답을 주세요.",
         "duo":[("여름","땀·눈물에 빠짐"),("환절기","모가 약해짐")],
         "punch":"걱정이 있을 때 <span class=\"blue\">지갑이</span> 열려요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“요즘 땀 때문에 더 잘 빠져요.<br><span class=\"blue\">이맘때</span> 받쳐주는 게 중요해요”",
         "note":"계절 걱정 → 해결책으로 자연 연결. # 시즌 소구"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"시즌 제안, 하고 있나?",
         "items":["사계절 <b>같은 멘트</b>만 쓴다","‘지금’ 사야 할 <b>이유가</b> 없다",
                  "계절 <b>걱정</b>을 안 건드린다","성수기 <b>준비</b>를 안 한다"],
         "footer":"계절이 <b class=\"blue\">구매 타이밍</b>을 만듭니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"이번 계절 걱정<br>하나로 멘트 만들기:",
         "quote":"“이맘때 빠지기 쉬워요, 받쳐줘야 해요”",
         "note":"<b>계절 + 걱정</b> 한 문장."},
        {"type":"closer","badge":"한 끗 차이","title":"필요성에<br><span class=\"hl\">‘지금’</span>을 심어라",
         "note":"같은 제품도 ‘지금 필요한 이유’가 붙으면 바로 팔립니다.",
         "punch":"미루면 <span class=\"blue\">안 삽니다</span>","tag":"# 긴급성"},
    ]},

    # 06 ─ "귀찮아요" 간편함 공략
    {"slug":"easy-care", "cards":[
        {"type":"cover",
         "title":"“관리 귀찮아요”는<br><span class=\"hl\">간편함</span>으로 뚫어요",
         "sub":"바쁜 고객일수록 <b>‘딱 하나’</b>가 먹힙니다"},
        {"type":"statement","title":"‘귀찮다’는<br>거절이 아니에요",
         "note":"안 하겠다는 게 아니라 ‘복잡하면 안 할래’라는 뜻입니다.",
         "lead":"복잡해 보이면 <span class=\"blue\">시작조차</span> 안 합니다.",
         "tag":"# 진입 장벽"},
        {"type":"point","badge":"핵심 포인트","title":"‘<span class=\"hl\">이거 하나면 끝</span>’으로 줄여라",
         "note":"할 일을 늘리지 말고, ‘자기 전에 한 번’처럼 딱 하나로 단순화하세요.",
         "duo":[("단계 많음","포기"),("딱 하나","지속")],
         "punch":"쉬워 보여야 <span class=\"blue\">삽니다</span>"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“복잡한 거 아니에요.<br><span class=\"blue\">자기 전에 한 번</span>, 그거면 돼요”",
         "note":"부담을 ‘한 번’으로 줄이기. # 단순화"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"괜히 어렵게 팔고 있진 않나?",
         "items":["사용법을 <b>길게</b> 설명한다","단계를 <b>여러 개</b> 나열한다",
                  "‘꾸준히’만 <b>강조</b>한다","‘얼마나 쉬운지’를 <b>안</b> 말한다"],
         "footer":"쉬워 보이게 <b class=\"blue\">줄이는</b> 게 기술"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"설명 길게 말고<br>딱 한 줄로:",
         "quote":"“자기 전에 한 번이면 끝이에요”",
         "note":"사용법을 <b>한 문장</b>으로 압축."},
        {"type":"closer","badge":"한 끗 차이","title":"파는 건 제품,<br>지우는 건 <span class=\"hl\">부담</span>",
         "note":"고객이 느끼는 ‘귀찮음’을 줄여주는 쪽이 결국 팝니다.",
         "punch":"쉬우면 <span class=\"blue\">계속 써요</span>","tag":"# 지속률"},
    ]},

    # 07 ─ 망설이는 고객 '지금' 만들기
    {"slug":"urgency", "cards":[
        {"type":"cover",
         "title":"“다음에 올게요”를<br><span class=\"hl\">오늘</span>로 바꾸는 법",
         "sub":"망설임은 <b>미룰 이유</b>가 많아서예요"},
        {"type":"statement","title":"‘다음에’는<br>대부분 안 와요",
         "note":"나가서 식으면 끝. ‘다음에’의 90%는 안 돌아옵니다.",
         "lead":"지금 안 하면 <span class=\"blue\">더 손해</span>라는 이유를 주세요.",
         "tag":"# 결정 미루기"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">미루는 비용</span>을 보여줘라",
         "note":"‘지금 사면 이득’보다 ‘안 하면 지금도 빠지는 중’이 더 움직입니다.",
         "duo":[("지금","받쳐주기 시작"),("미루면","계속 약해짐")],
         "punch":"사람은 <span class=\"blue\">손해</span>에 더 민감해요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“고민하시는 동안에도<br><span class=\"blue\">지금 계속</span> 빠지고 있는 거예요”",
         "note":"재촉이 아니라 ‘현실’을 짚기. # 손실 회피"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"망설임, 그냥 보내고 있나?",
         "items":["“다음에요”에 <b>그냥</b> 보낸다","미루면 생기는 <b>손해를</b> 안 짚는다",
                  "오늘만의 <b>이유가</b> 없다","결정할 <b>한 문장</b>을 안 준다"],
         "footer":"‘지금’을 안 주면 <b class=\"blue\">안 옵니다</b>"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"“다음에” 들으면<br>재촉 말고:",
         "quote":"“고민하는 지금도 빠지는 중이에요”",
         "note":"<b>미루는 비용</b> 한 문장."},
        {"type":"closer","badge":"한 끗 차이","title":"‘지금’을<br><span class=\"hl\">만들어</span>줘라",
         "note":"고객은 스스로 ‘지금’을 못 만듭니다. 그걸 만들어주는 게 세일즈입니다.",
         "punch":"오늘을 놓치면 <span class=\"blue\">끝</span>","tag":"# 긴급성"},
    ]},

    # 08 ─ 선물 수요로 객단가
    {"slug":"gift", "cards":[
        {"type":"cover",
         "title":"‘내 거’ 말고<br><span class=\"hl\">‘선물용’</span>도 파세요",
         "sub":"한 명이 사면 <b>두 개</b> 나가는 법"},
        {"type":"statement","title":"고객은<br>선물할 걸 늘 찾아요",
         "note":"친구·엄마·동생… 눈썹 고민은 다들 비슷합니다.",
         "lead":"‘선물’ 한마디면 <span class=\"blue\">객단가가 두 배</span>가 됩니다.",
         "tag":"# 숨은 수요"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">‘같이 쓰면 좋은 사람’</span>을 떠올리게",
         "note":"내 것만 생각하던 고객에게 ‘선물’이라는 선택지를 열어주세요.",
         "duo":[("1개","내 것만"),("+선물","둘이 씀")],
         "punch":"선물은 <span class=\"blue\">가격 저항</span>이 적어요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“눈썹 고민하는 분 주변에 꼭 있잖아요.<br><span class=\"blue\">선물로도</span> 반응 좋아요”",
         "note":"내 것 + 선물 동시 제안. # 교차 판매"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"선물 수요, 놓치고 있나?",
         "items":["‘본인용’으로만 <b>판다</b>","선물 <b>포장</b>이 없다",
                  "기념일·시즌 <b>제안이</b> 없다","‘주변에 추천’을 <b>안</b> 권한다"],
         "footer":"선물은 <b class=\"blue\">한 명이 둘</b>을 삽니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"구매 결정되면<br>한마디 더:",
         "quote":"“선물로도 하나 어떠세요?”",
         "note":"결제 직전 <b>선물 제안</b> 한 번."},
        {"type":"closer","badge":"한 끗 차이","title":"한 번 올 때<br><span class=\"hl\">두 개</span> 팔기",
         "note":"같은 고객, 같은 방문. 선물 한마디로 객단가가 올라갑니다.",
         "punch":"제안 안 하면 <span class=\"blue\">0개</span>","tag":"# 객단가"},
    ]},

    # 09 ─ 소개(입소문) 터뜨리기
    {"slug":"referral", "cards":[
        {"type":"cover",
         "title":"고객이 고객을<br><span class=\"hl\">데려오게</span> 만드는 법",
         "sub":"제일 센 광고는 <b>단골의 입</b>"},
        {"type":"statement","title":"만족한 고객도<br>그냥은 소개 안 해요",
         "note":"좋아도 ‘먼저 말할 이유’가 없으면 입을 안 엽니다.",
         "lead":"소개는 저절로 안 터져요. <span class=\"blue\">계기</span>를 줘야 합니다.",
         "tag":"# 입소문 설계"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">자랑거리</span>를 손에 쥐여줘라",
         "note":"효과 본 고객에게 ‘말하기 쉬운 한마디’와 혜택을 주면 소개가 돕니다.",
         "duo":[("그냥 만족","조용함"),("자랑거리+혜택","소개함")],
         "punch":"말할 <span class=\"blue\">이유</span>를 주세요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“효과 보셨으면 친구분도요,<br><span class=\"blue\">같이 오시면</span> 두 분 다 챙겨드려요”",
         "note":"소개=둘 다 이득 구조로. # 추천 보상"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"소개, 그냥 기다리고만 있나?",
         "items":["소개를 <b>먼저</b> 권하지 않는다","추천 <b>혜택이</b> 없다",
                  "만족한 순간을 <b>안</b> 짚는다","‘같이 와요’를 <b>안</b> 말한다"],
         "footer":"소개는 <b class=\"blue\">설계</b>해야 터집니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"효과 좋다는 고객에게<br>그 자리에서:",
         "quote":"“친구분이랑 같이 오세요”",
         "note":"만족한 <b>그 순간</b>에 한마디."},
        {"type":"closer","badge":"한 끗 차이","title":"단골 한 명이<br><span class=\"hl\">신규 세 명</span>",
         "note":"광고비 0원. 만족한 단골의 입이 가장 강한 영업입니다.",
         "punch":"믿음은 <span class=\"blue\">전염</span>돼요","tag":"# 소개 영업"},
    ]},

    # 10 ─ 단골·VIP 특별 제안
    {"slug":"vip", "cards":[
        {"type":"cover",
         "title":"단골에게만 주는<br><span class=\"hl\">특별함</span>으로 재구매",
         "sub":"매출의 8할은 <b>단골</b>에서 나옵니다"},
        {"type":"statement","title":"단골을<br>당연하게 여기면 떠나요",
         "note":"신규만 쫓다 보면, 정작 매출을 떠받치는 단골이 서운해합니다.",
         "lead":"단골은 <span class=\"blue\">‘특별 대우’</span>에 가장 크게 반응합니다.",
         "tag":"# 리텐션"},
        {"type":"point","badge":"핵심 포인트","title":"<span class=\"hl\">‘당신만’</span>이라는 느낌을 줘라",
         "note":"누구나 받는 할인이 아니라, ‘단골이라서’ 주는 제안이 마음을 움직입니다.",
         "duo":[("전체 할인","흔함"),("단골 전용","특별함")],
         "punch":"특별 대우엔 <span class=\"blue\">보답</span>이 와요"},
        {"type":"mentte","badge":"실전 멘트",
         "quote":"“항상 와주시니까,<br><span class=\"blue\">단골님만</span> 이렇게 챙겨드리는 거예요”",
         "note":"‘당신이라서’를 분명히 말하기. # 특별감"},
        {"type":"checklist","badge":"체크포인트 · 자가진단","title":"단골, 챙기고 있나?",
         "items":["단골·신규를 <b>똑같이</b> 대한다","단골 <b>전용 혜택이</b> 없다",
                  "방문 이력을 <b>기억</b> 못 한다","‘덕분에’ 한마디를 <b>안</b> 한다"],
         "footer":"단골 관리가 <b class=\"blue\">재구매율</b>입니다"},
        {"type":"apply","badge":"이번 주 적용해보기",
         "lead":"단골이 올 때<br>특별함 한 문장:",
         "quote":"“단골님이라 따로 챙겨드려요”",
         "note":"‘당신만’ 느낌 <b>한 번</b>씩."},
        {"type":"closer","badge":"한 끗 차이","title":"신규보다<br><span class=\"hl\">단골</span>이 남는다",
         "note":"새 고객 모으는 비용보다, 단골 한 명 지키는 게 훨씬 쌉니다.",
         "punch":"오래 가는 매출은 <span class=\"blue\">단골</span>","tag":"# 단골 경영"},
    ]},
]
